# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev, master, 'feat/*']
  pull_request:
    branches: [dev, master, 'feat/*']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')"
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          node: ["16"]
    name: install - ${{ matrix.os }} - ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - name: Install dependencies
        run: |
          yarn
  # test:
  #   needs: install
  #   strategy:
  #       matrix:
  #         os: [ubuntu-latest, macos-latest, windows-latest]
  #         node: ["16"]
  #   name: test - ${{ matrix.os }} - ${{ matrix.node }}
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - name: Load node_modules
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           node_modules
  #           */*/node_modules
  #         key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
  #     - run: yarn test
  lint:
    needs: install
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          node: ["16"]
    name: lint - ${{ matrix.os }} - ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Load node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - run: yarn lint
  build:
    needs: [lint]
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          node: ["16"]
    name: build - ${{ matrix.os }} - ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Load node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_output
          path: bin

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_output
          path: bin
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: zhangyuang/ssr
          path: ssr
          ref: dev
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: zhangyuang/micro-app-ssr
          path: micro-app-ssr
          ref: master

      - name: Publish
        run: | 
          cp -R ./ssr/example/ ./
          cp -R ./micro-app-ssr ./example
          rm -rf ssr
          rm -rf ./micro-app-ssr
          rm -rf ./nestjs-vue3-ssr-pinia
          ls
          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish
          else
            echo "Not a release, skipping publish"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}